# These are supported funding model platforms

github: Myzel394
custom: ["btc:bc1qw054829yj8e2u8glxnfcg3w22dkek577mjt5x6", "xmr:83dm5wyuckG4aPbuMREHCEgLNwVn5i7963SKBhECaA7Ueb7DKBTy639R3QfMtb3DsFHMp8u6WGiCFgbdRDBBcz5sLduUtm8"]
