const SPACE_MULTIPLIER = 2.0;

const TINY_SPACE = SPACE_MULTIPLIER * 2;
const SMALL_SPACE = SPACE_MULTIPLIER * 5;
const MEDIUM_SPACE = SPACE_MULTIPLIER * 10;
const LARGE_SPACE = SPACE_MULTIPLIER * 20;
const HUGE_SPACE = SPACE_MULTIPLIER * 40;
